<?php

namespace BlogBundle\Repository;

/**
 * News_to_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class News_to_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
