BlogBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
    lifecycleCallbacks: {  }

    oneToMany:
        relations:
            targetEntity: News_to_category
            mappedBy: categories