BlogBundle\Entity\News_to_category:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\News_to_categoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        newsId:
            type: integer
            column: news_id
        categoryId:
            type: integer
            column: category_id
    lifecycleCallbacks: {  }

    manyToOne:
            news:
                targetEntity: News
                inversedBy: relations
                joinColumn:
                    name: news_id
                    referencedColumnName: id
            categories:
                targetEntity: Category
                inversedBy: relations
                joinColumn:
                    name: category_id
                    referencedColumnName: id


