BlogBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        newsId:
            type: integer
            column: news_id
        tag:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        news:
            targetEntity: News
            inversedBy: tags
            joinColumn:
                name: news_id
                referencedColumnName: id
